### ISSUE TITLE
组态信息、组态模板

### ISSUE THREAD

**Issue by adgvveq** [dgiot/dgiot#10]
![image](https://user-images.githubusercontent.com/55369101/127251908-4a120f2c-6519-487d-9b26-fe40e097a98b.png)
你好，请问这个界面是没有做出来吗。另外组态最终呈现的效果图是怎么样的，我后期想借用你们的模板方便移植吗。

**Comment by h7ml** [comment]
已修復。可移植。基于[konvajs](https://konvajs.org/docs/)
