### ISSUE TITLE
物联网erlang代码解析求助

### ISSUE THREAD

**Issue by zxvmra** [dgiot/dgiot#11]
![image](https://user-images.githubusercontent.com/55369161/127252913-4be6046c-be08-48f3-b94d-0d9afe52d9f6.png)
![image](https://user-images.githubusercontent.com/55369161/127252932-0856f561-c11d-460e-a36a-26a33e1ee5f2.png)
请问为什么要首发两个数据段？前面那句是获取数据地址后面那段是利用devaddr做一个数据接受然后获取数据是吗？

**Comment by crikayuan** [comment]
没听懂你的意思。前面是首次上传的设备标识比如MAC、SN什么的，后面是数据的收发。解析放在最后面了。

**Comment by lsxredrain** [comment]
modbus设备本身是没有唯一设备地址的，必须借助dtu的地址来间接标识modbus设备的唯一地址，所以首先需要dtu发登陆报文来标识dtu的唯一地址，然后modbus设备通过modbus地址+dtu的设备地址组合实现modbus设备唯一地址

**Comment by lsxredrain** [comment]
modbus设备本身是没有唯一设备地址的，必须借助dtu的地址来间接标识modbus设备的唯一地址，所以首先需要dtu发登陆报文来标识dtu的唯一地址，然后modbus设备通过modbus地址+dtu的设备地址组合实现modbus设备唯一地址
