### ISSUE TITLE
The personal center can't be accessed

### ISSUE THREAD

**Issue by USF6688** [dgiot/dgiot#113]
**Environment**:

- dgiot version (e.g. `dgiot_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:

**What happened and what you expected to happen**:
The personal center can't be accessed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/91302296/134613450-bb8d4093-8b64-4429-8d84-d5c34acefdd1.png)

**Comment by h7ml** [comment]
hi. The reason why this link cannot jump to the personal center is because there is no corresponding menu configured.

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/134637301-a4249cb2-54ab-475d-b603-44d3791e6f0b.png)

done
