### ISSUE TITLE
动态表单

### ISSUE THREAD

**Issue by zxcvbasdn** [dgiot/dgiot#12]
![image](https://user-images.githubusercontent.com/55369235/127262021-17dde445-ed2e-4e04-a165-1afe1a75e089.png)
![image](https://user-images.githubusercontent.com/55369235/127262048-f1f8c21a-1ff7-45e3-894b-05db190ad9c2.png)
**这里有12条信息，单独显示10条/页时另外两个通道无法正常显示望做出处理。**

**Comment by crikayuan** [comment]
已处理

**Comment by h7ml** [comment]
[5945848](https://github.com/dgiot/dgiot_dashboard/commit/5945848b71a407afbb4cd687005208a970112192)
