### ISSUE TITLE
演示电表DTU 的物模型下没有下发指令，电表的数据是如何获取的？

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#129]
演示电表DTU 的物模型下没有下发指令，电表的数据是如何获取的？
![image](https://user-images.githubusercontent.com/90950289/134803539-5b8b2f09-34d9-4d2a-9be4-63315525c107.png)

**Comment by AvantLiu** [comment]
![image](https://user-images.githubusercontent.com/47805007/134803589-4273b094-52b0-492b-8f58-e879af0a65e1.png)
根据电表协议自己添加想要获取的数据的物模型地址
