### ISSUE TITLE
通道集成

### ISSUE THREAD

**Issue by dvasdfva** [dgiot/dgiot#13]
平台产品只支持一个端口连接。因为dtu只支持一个端口那就只能支持一个通道的连接。那比如我想将一个Modbus协议的设备和一个电表设备接在一个DTU下连上平台。但基于这个情况需要在平台启用两个通道。就是以目前的连接方式无法完成。所以我想问问能不能把连个通道集成到一个端口进行通讯。完成多个不同协议设备的同时接入可以把。

![image](https://user-images.githubusercontent.com/55369307/127956041-6d37a68f-8aa7-44f1-9244-fb3ee8563ca2.png)

**Comment by lsxredrain** [comment]
针对这种场景，我们采用的解决方案是通过通道里面挂载解码器的方式来解决，例如开启一个tcp通道，tcp只处理dtu的登入，登出，dtu下面挂载的modbus设备，电表设备则通过产品自带的解码器来解析传感器的业务报文
