### ISSUE TITLE
Generally, the module of the 4g meter adopts the 376 protocol, which is not a transparent transmission mode. Does the platform directly support it?

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#135]
Generally, the module of the 4g meter adopts the 376 protocol, which is not a transparent transmission mode. Does the platform directly support it?

**Comment by lsxredrain** [comment]
In the future, you can select 376 protocol in the object model for direct support. The internal test has passed, and will open source to our product store in the future
