### ISSUE TITLE
账号间设备隔离，不共享。

### ISSUE THREAD

**Issue by zxq2233** [dgiot/dgiot#14]
**What would you like to be added/modified**:

**Why is this needed**:

**Comment by crikayuan** [comment]
分配合适的权限给相应的角色,然后创建各个用户绑定所对应的权限.达到不同用户间设备信息保密的效果.
![image](https://user-images.githubusercontent.com/62696005/128652471-c5a62f20-b6f3-400d-9860-d02bbc816aaf.png)

**Comment by lsxredrain** [comment]
dgiot权限包括三个方面，1、功能权限（API打勾去勾）；2、菜单权限(菜单打勾去勾），3、数据权限（ACL），产品/设备/通道/字典都是资源，这些资源都有一个ACL选项，支持部门继承，ACL有role或者子role就有可以访问，通过ACL来做设备隔离

**Comment by zxq2233** [comment]
我在角色下创建了多个账号。我发现每个账号都有显示设备。

**Comment by h7ml** [comment]
> 我在角色下创建了多个账号。我发现每个账号都有显示设备。

因为账号是与部门关联的。你的多个账号，是在同一个部门下。所以，这些账号能看到同部门和这个部门下所有其他部门的设备
