### ISSUE TITLE
Installation and deployment

### ISSUE THREAD

**Issue by Aaaa-mber** [dgiot/dgiot#17]
一键部署的工具包在哪里啊？

**Comment by hzkyhao** [comment]
Read the following link description first, and then follow the instructions.
https://github.com/dgiot/dgiot/blob/master/README-CN.md，

**Comment by lsxredrain** [comment]
wget -q https://gitee.com/dgiiot/dgiot/raw/master/dgiot_install.sh  && sh dgiot_install.sh
