### ISSUE TITLE
There is a problem with the page after the delete operation in the dictionary management

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#187]
![image](https://user-images.githubusercontent.com/90950289/139655782-fb068c0a-7fd2-4201-a725-f70e16226fd0.png)
![image](https://user-images.githubusercontent.com/90950289/139655804-aa63779a-0fa9-4f2e-88de-5e0e374b7907.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
