### ISSUE TITLE
My query result on the ticket page is incorrect

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#188]
If you choose to be assigned, all the data is found, and the rest of the status queries are normal
![image](https://user-images.githubusercontent.com/90950289/139656941-6e4dd0a9-339e-418b-bec4-519fe87d8e40.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
