### ISSUE TITLE
The creation time of the device in the device management is incorrect

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#190]
The creation time of the device in the device management is incorrect

**Comment by h7ml** [comment]
The fixed display time is Beijing time
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
