### ISSUE TITLE
The layout of product management needs to be adjusted

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#191]
In product management, in my product, the product operation buttons are not neatly arranged on a small screen
![image](https://user-images.githubusercontent.com/51999461/139783613-10a2d28f-ed59-4eff-8743-f5b7e46c5c9b.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
