### ISSUE TITLE
The input text is not detailed

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#192]
There are too few prompts to the user, such as data type, unit, recommended value range, etc., which is easy for users to set errors.
![image](https://user-images.githubusercontent.com/51999461/139783735-a123f3f0-62c5-48a1-835c-ddd6bc4131f3.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
