### ISSUE TITLE
The role management search function is abnormal

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#193]
![image](https://user-images.githubusercontent.com/51999461/139783845-25421e72-2e35-4da1-9e5e-3511e37b124f.png)
![image](https://user-images.githubusercontent.com/51999461/139783863-27cb62f6-9a26-4dc2-a02b-e7e3304388e6.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
