### ISSUE TITLE
Exported products are exported as empty

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#194]
Export in product management
![image](https://user-images.githubusercontent.com/51999461/139784040-d0114a98-43da-4d5e-824e-6cf10d9d8593.png)
There is only one Dict file after decompression
![image](https://user-images.githubusercontent.com/51999461/139784074-4a6e272f-46cf-4485-b90e-f35d3f38ad21.png)
![image](https://user-images.githubusercontent.com/51999461/139784091-44cc2dfc-ab2a-442f-a522-7d9fb5fb74b8.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
