### ISSUE TITLE
After deleting the device, no more devices can be added

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#195]
After deleting a device, can't add it anymore?

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
