### ISSUE TITLE
Password settings for user management are not verified

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#196]
When creating a new user, the user password was not verified. For example, when I set a 3-digit password, the new creation was successful, and then when I log in to the new account, it prompts that the password cannot be less than 4 digits.

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
