### ISSUE TITLE
Pagination problem of product template

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#197]
After selecting 5 items per page, the requested page does not change. After selecting 10 items per page, the requested page is displayed as 5 items per page.
![image](https://user-images.githubusercontent.com/90950289/139786581-4a945ca1-3e5b-4b65-a65a-c8b74fc566a3.png)

![image](https://user-images.githubusercontent.com/90950289/139786598-0964ce69-bd6e-4a5b-979e-e5f013d924eb.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
