### ISSUE TITLE
Pagination problem of category management

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#198]
Category management When there are 5 entries per page, there are 3 pages in total, but clicking the "2" button will jump to the third page
![image](https://user-images.githubusercontent.com/90950289/139786700-1bc3b062-39a5-4ea6-8d59-ecd6c5567147.png)
When there are 10 entries per page, there are 3 pages in total, but the first page only has the data shown in the figure
![image](https://user-images.githubusercontent.com/90950289/139786757-a9958cd4-2066-4882-b516-737ce6724c33.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
