### ISSUE TITLE
What is the dictionary template for

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#199]
![image](https://user-images.githubusercontent.com/90950289/139786851-f90d02ff-5ac1-48d6-af12-15efe18fe27c.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
