### ISSUE TITLE
Abnormal display of interface management data

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#200]
The interface management displays 428 items of data, but the list has only 8 items of data
And no matter how you choose the page number, it shows that there is no data yet, even if you jump back to the first page, there is no data.
![image](https://user-images.githubusercontent.com/90950289/139786959-951a41ec-f5b1-4fc6-96e4-2acf5b69b6d4.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
