### ISSUE TITLE
In the new custom attribute option of the object model, the icon cannot be uploaded

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#201]
In the new custom attribute option of the object model, the icon cannot be uploaded

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
