### ISSUE TITLE
Is the name of the compressed package exported by the product garbled?

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#202]
Is the name of the compressed package exported by the product garbled?

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
