### ISSUE TITLE
No response to deletion of configuration screen

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#203]
![image](https://user-images.githubusercontent.com/51999461/140292866-b2abf157-cdda-4975-9e89-b6595f265fe2.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
