### ISSUE TITLE
创建工单所属项目的产品数量不对

### ISSUE THREAD

**Issue by xuxiaobo1010** [dgiot/dgiot#205]
产品列表里面有20多个但是创建工单的时候只显示这四个
![dc32f3e32250eadb62bd36531cee506](https://user-images.githubusercontent.com/73056200/141425468-2ce02965-ca3d-4b1e-9423-81f4b5fb307b.jpg)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
