### ISSUE TITLE
平台无法解析mudbus协议长数量数据

### ISSUE THREAD

**Issue by xuxiaobo1010** [dgiot/dgiot#206]
mudbus协议，一次性数据上发，平台无法解析，应该要做到，整块采集，分块存库。提个小功能。
![815ce32ba3c53e462ac59c8d60afcfd](https://user-images.githubusercontent.com/73056200/141425687-dc13675d-588c-4754-b143-13e5cc830ed0.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
