### ISSUE TITLE
The total number of point products page does not exist

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#209]
![image](https://user-images.githubusercontent.com/51999461/143358471-b33c3a81-fcb3-4e41-93ba-e31bd50123df.png)
![image](https://user-images.githubusercontent.com/51999461/143358541-4aeb8980-cc92-4973-bcf8-4b959178a92a.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
