### ISSUE TITLE
The prompt for overtime is changed to "Save job template"

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#210]
![image](https://user-images.githubusercontent.com/51999461/143359655-f28e7a71-1090-4716-a527-e33e8ec46c67.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
