### ISSUE TITLE
The switch department tree button is commonly used, it is recommended to make it more conspicuous, at least there must be a hint

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#212]
![image](https://user-images.githubusercontent.com/51999461/143361546-960a105b-e964-48b2-ae7f-863fee0cca0b.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
