### ISSUE TITLE
The total number of products and the total number of devices in the master console is not accurate

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#213]
![image](https://user-images.githubusercontent.com/51999461/143375680-fd740cd7-02e1-4f43-885f-3a068fe8df63.png)
Two new products and equipment are created, but the display is still 0

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
