### ISSUE TITLE
The drop-down box for selecting a product when there are products and equipment in the creation of a work order is not displayed

### ISSUE THREAD

**Issue by wanguliux** [dgiot/dgiot#214]
![image](https://user-images.githubusercontent.com/51999461/143375835-062c7d42-3df9-4f9d-b52e-81ded8a79c3b.png)

**Comment by h7ml** [comment]
This problem has been fixed in version  [dgiot-dashboard 4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0). Please update the front end to [4.4.0](https://github.com/dgiot/dgiot-dashboard/releases/tag/v4.4.0)
