### ISSUE TITLE
设备连接成功但是界面显示离线

### ISSUE THREAD

**Issue by wwhai** [dgiot/dgiot#216]
设备连接成功但是界面显示离线：
![d171a815b5ce410e188f32138d31b92](https://user-images.githubusercontent.com/20577297/148634355-23659b71-5196-4ec0-8677-ad65dc47ac8c.png)
![image](https://user-images.githubusercontent.com/20577297/148634362-628a4177-ebfc-42d8-95a9-bff5565257f2.png)

**Comment by lsxredrain** [comment]
[7a5336c22404611d8a1845af1c6232a92930d6d8](https://github.com/dgiot/dgiot/commit/7a5336c22404611d8a1845af1c6232a92930d6d8)
增加mqtt上下线快速状态修改判断
