### ISSUE TITLE
删除通道后，资源沒有同步更新，导致规则里面出现了脏数据

### ISSUE THREAD

**Issue by wwhai** [dgiot/dgiot#217]
![image](https://user-images.githubusercontent.com/20577297/148639206-0d39116f-9545-4df3-876f-4808193646cc.png)
删除通道后，资源沒有同步更新，导致规则里面出现了脏数据：
## 下面这个规则实际上是脏数据
![image](https://user-images.githubusercontent.com/20577297/148639233-122b4719-825a-4402-9d86-0a67376dc93e.png)

**Comment by h7ml** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
