### ISSUE TITLE
设备云_设备详情_安装位置修改后，下方地图未变化，其他地图位置变化了（总控台，设备地图等）

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#224]
![190839_d0df83b4_376964](https://user-images.githubusercontent.com/90950289/151099109-ad2cf2a0-5aee-4df8-8904-3abb618623d4.png)
通知地图的初始中心位置，建议增加配置

**Comment by wanguliux** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
