### ISSUE TITLE
创建工单时选择的所属项目数量不对

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#226]
产品列表里有20几个但是这里选择的时候只显示了4个
![image](https://user-images.githubusercontent.com/90950289/151102520-5f1a269f-6be3-4413-87b3-e05a16ffd0c3.png)

**Comment by wanguliux** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
