### ISSUE TITLE
Cannot read properties of undefined (reading 'init')

### ISSUE THREAD

**Issue by real-baiye** [dgiot/dgiot#230]
TypeError: Cannot read properties of undefined (reading 'init') at a.init (http://localhostv:30080/dgiot_dashboard/public/assets/js/index.min.js:1:19309) at a.mounted (http://localhostv:30080/dgiot_dashboard/public/assets/js/index.min.js:1:20717) at Be (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:11407) at Qt (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:25438) at Object.insert (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:20517) at k (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:60576) at a.patch (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:61934) at a.e._update (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:34592) at a.r (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:68555) at pn.get (http://localhostv:30080/dgiot_dashboard/public/assets/js/vue.min.js:6:26867)

docker容器跑dgiot/dgiot的容器上面，运行后刷新的到以上前端bug

**Comment by wanguliux** [comment]
The problem is in [dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8) Resolved
