### ISSUE TITLE
DGIOT的平台，系统后端有JAVA语言的吗？我们能否用JAVA做二次开发啊？

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#232]
准备在DGIOT平台上，想用JAVA语言做二次开发？请教下。

**Comment by wanguliux** [comment]
底层是Erlang语言写的，可以通过我们提供的openAPI，MQTT订阅，gRPC，port，cmd等方式兼容其他语言进行二次开发，例如java，python，lua，c，c++，c#等
