### ISSUE TITLE
有没有针对云服务器的物联网平台安装镜像包，方便快速在各个云服务器厂商平台快速部署DGIOT平台？

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#234]
有没有针对腾讯云、阿里云、华为云、天翼云、青云和Docker、VMWare等虚拟机上，方便快速部署DGIOT平台？

**Comment by wanguliux** [comment]
有的，具体可见这个链接https://gitee.com/dgiiot/dgiot/wikis
