### ISSUE TITLE
有支持国网和南网的集中器模拟器吗？还有就是平台现在有对国网和南网规约的集中器协议支持吗？

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#238]

**Comment by wanguliux** [comment]
国网南网模拟集中区器可以看一下这个报告，[https://gitee.com/dgiiot/dgiot/wikis/%E4%BA%A7%E5%93%81%E6%89%8B%E5%86%8C/%E4%BA%91%E5%8E%8B%E6%B5%8B/%E5%8E%8B%E6%B5%8B%E6%8A%A5%E5%91%8A/3000%E4%B8%87%E7%9C%81%E7%BA%A7%E7%94%B5%E8%A1%A8%E9%9B%86%E6%8A%84%E5%8E%8B%E6%B5%8B，](https://gitee.com/dgiiot/dgiot/wikis/%E4%BA%A7%E5%93%81%E6%89%8B%E5%86%8C/%E4%BA%91%E5%8E%8B%E6%B5%8B/%E5%8E%8B%E6%B5%8B%E6%8A%A5%E5%91%8A/3000%E4%B8%87%E7%9C%81%E7%BA%A7%E7%94%B5%E8%A1%A8%E9%9B%86%E6%8A%84%E5%8E%8B%E6%B5%8B%EF%BC%8C)
国网和南网的集中器模拟器还不适合开放，下载平台支持DLT845和国网4G集中区器的简单接入
