### ISSUE TITLE
Sort not available

### ISSUE THREAD

**Issue by zhouzishany** [dgiot/dgiot#25]
![image](https://user-images.githubusercontent.com/73293143/132793665-fbd788c0-c689-41ee-ae8f-e56a39518533.png)

**Comment by zhouzishany** [comment]
设备管理排序的也无法使用👇
![image](https://user-images.githubusercontent.com/73293143/132793830-f2c84910-c87e-48ae-80e7-6d1f81e53ad3.png)

**Comment by lsxredrain** [comment]
@h7ml
