### ISSUE TITLE
前端_设备详情_历史数据，无法显示，Cannot Read property setOption

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#250]
![image](https://user-images.githubusercontent.com/93361221/151663697-ea4544f7-c1f3-4d6f-83ad-7c883e2acac1.png)
![image](https://user-images.githubusercontent.com/93361221/151663703-e4b2056b-ab03-4c44-ad23-08f5cc602d0e.png)

**Comment by h7ml** [comment]
fixed
