### ISSUE TITLE
导出产品导出为空

### ISSUE THREAD

**Issue by H7993** [dgiot/dgiot#26]
**产品管理中导出**
![image](https://user-images.githubusercontent.com/90435296/132794809-f2dc18ef-a049-4c80-ae88-a230be81d810.png)

**解压后只有一个Dict文件**
![image](https://user-images.githubusercontent.com/90435296/132794737-1cdb20df-162e-4243-8ed1-e36049b06e55.png)

![image](https://user-images.githubusercontent.com/90435296/132794710-3ec823eb-e12f-4cf3-b808-2555b64d64bb.png)

**Comment by h7ml** [comment]
已修复
