### ISSUE TITLE
总控台的产品总数和设备总数不准确

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#270]
新建了两个设备和产品了，但是显示为0
![image](https://user-images.githubusercontent.com/93361221/151808364-8638fa40-be11-426c-9c12-6ebebb209db5.png)

**Comment by wanguliux** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
