### ISSUE TITLE
组态，双击无法弹窗

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#277]
![image](https://user-images.githubusercontent.com/93361221/151965899-56f19dd2-fa8d-46f7-abb0-7ec06484af6c.png)

**Comment by h7ml** [comment]
fixed

**Comment by wanguliux** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
