### ISSUE TITLE
DGIOT是否支持JAVA的二次开发？如果支持的话，是通过哪种方式来调用的？多谢

### ISSUE THREAD

**Issue by east-spider** [dgiot/dgiot#282]
**What would you like to be added/modified**:

**Why is this needed**:

**Comment by wanguliux** [comment]
底层是Erlang语言写的，可以通过我们提供的openAPI，MQTT订阅，gRPC，port，cmd等方式兼容其他语言进行二次开发，例如java，python，lua，c，c++，c#等
