### ISSUE TITLE
我的工单页面查询结果有误

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#287]
如果选择待分配，查到的是全部的数据，其余状态查询均为正常
![image](https://user-images.githubusercontent.com/93361221/152295012-16915980-6945-4327-ab4e-f69141795cd7.png)

**Comment by wanguliux** [comment]
该问题在[dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8)已解决
