### ISSUE TITLE
export product export is empty

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#297]
Export in product management
![image](https://user-images.githubusercontent.com/93361221/152479657-3440443d-8cfe-4ef7-b5cc-54853eb5281f.png)
There is only one Dict file after decompression
![image](https://user-images.githubusercontent.com/93361221/152479686-8b193869-7923-494b-9ba4-c143490b6a6a.png)
![image](https://user-images.githubusercontent.com/93361221/152479692-14f30d30-8e1b-4b72-b06f-10de135a11ed.png)

**Comment by wanguliux** [comment]
The problem is in [dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8) Resolved
