### ISSUE TITLE
What is a dictionary template for?

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#312]
What is a dictionary template for?
![image](https://user-images.githubusercontent.com/93361221/152631750-b85e6824-ea9d-4fbc-abac-d40de0c54e7e.png)
![image](https://user-images.githubusercontent.com/93361221/152631751-e2f47410-35e2-4d8d-8c1b-e3d9192dad8d.png)

**Comment by wanguliux** [comment]
Used to configure device information or control
