### ISSUE TITLE
Device data is not updated in time

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#320]
The update time is sometimes half an hour ago, sometimes an hour ago
![image](https://user-images.githubusercontent.com/93361221/152667679-4d2a6a6b-2355-4791-aeb9-f565f8205b2b.png)

**Comment by wanguliux** [comment]
The problem is in [dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8) Resolved
