### ISSUE TITLE
Configuration large screen no response

### ISSUE THREAD

**Issue by QiFeeng** [dgiot/dgiot#327]
**Environment**:

Success / Image loading completed, but no response
![image](https://user-images.githubusercontent.com/93361221/152735221-e7d0465a-6388-4452-a42e-8a4d573fe1a0.png)

**Comment by h7ml** [comment]
The problem is in [dgiot-4.4.8](https://gitee.com/dgiiot/dgiot/releases/v4.4.8) Resolved
