### ISSUE TITLE
创建工单时设备名称无法选择

### ISSUE THREAD

**Issue by Lunia-i** [dgiot/dgiot#33]
![image](https://user-images.githubusercontent.com/90381762/133013542-7a93ac50-2b73-45ed-ab38-d89aec58cddc.png)

**Comment by h7ml** [comment]
该项目下没有设备

**Comment by Lunia-i** [comment]
目前所有项目都没有设备吗？工单1631063813不是mqtt_test项目下的吗

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/133016303-b1911520-0620-4816-a369-bf41a1983043.png)
那台设备应该被删了
