### ISSUE TITLE
What are the rules for port numbers and Message frame headers？

### ISSUE THREAD

**Issue by moqw** [dgiot/dgiot#34]
**According to what rules are port numbers and frame headers set when creating modbus channels**

![image](https://user-images.githubusercontent.com/73354391/133018850-a891e9e0-2263-494b-98fb-0b0082975698.png)

**Comment by lsxredrain** [comment]
en:
Ports only need to ensure that the server port is not repeated. It is generally recommended that the ports that are not commonly used are used. The landing packets are equivalent to the ID number of the people. To ensure the uniqueness of the device identities, if MAC addresses are used, the MAC addresses should be arranged according to the rules of the MAC address. For example, if someone's MAC address is started with 9C-A5-25, it can be written into a wildcard such as 9C-A5-25-**-**-** to identify DTU. IMEI and other identifiers can also be used as login messages. The details should be based on the actual situation of the actual DTU. The main rule is to be able to distinguish who is who
cn:
端口只需要保证服务器端口不重复即可,一般建议用不太常用的端口, 登陆报文相当于人的身份证号码,要保证设备标识的唯一性,如果用MAC地址,就按MAC地址的规则编排,例如有人DTU的MAC地址是用9C-A5-25开头的,就可以写成9C-A5-25-**-**-**这样的通配符,来识别是不是有人的DTU,也可以用IMEI等标识来做登陆报文,具体要根据实际DTU的实际情况来,主要规则就是要能辨别除谁是谁
