### ISSUE TITLE
Channel has no logs

### ISSUE THREAD

**Issue by Chubery** [dgiot/dgiot#447]
![WBV0Y4DNY2J_2Z D4XG CHY](https://user-images.githubusercontent.com/76640514/170438214-d0586b43-f106-46a5-859a-bde7bfcf6907.png)
But in the precise log query, view the product's log precise log query
![WTY8BU{LGW$WMCWJE02{O@D](https://user-images.githubusercontent.com/76640514/170438330-94053f8f-d004-4917-b95f-312d9d5db077.png)
![~841_1F6)PW0B}$C@E7SIT](https://user-images.githubusercontent.com/76640514/170438336-df3c2667-a2a9-4ee4-9604-540d80b98d9a.png)

**Comment by h7ml** [comment]
Thanks for your feedback, the problem has been located and fixed
