### ISSUE TITLE
When searching for offline devices, the return is 0, but there is actually one device

### ISSUE THREAD

**Issue by LX1203Hui** [dgiot/dgiot#449]
![image](https://user-images.githubusercontent.com/75428936/170484830-940fafdb-3911-4faf-b77e-451419151707.png)
![image](https://user-images.githubusercontent.com/75428936/170484974-71064f94-fa62-4caf-86a2-bfda9ce82e40.png)

**Comment by h7ml** [comment]
Thanks for your feedback. the issue has been resolved
