### ISSUE TITLE
Why can't the product be created？

### ISSUE THREAD

**Issue by LX1203Hui** [dgiot/dgiot#481]
![DNL@B6UBLWO U2NS `0LD)X](https://user-images.githubusercontent.com/75428936/174509774-2cceccce-c281-47d7-8e70-816480d841f3.jpg)

**Comment by shifttttttt** [comment]
![)M%TO%N7P$VJ_F4(CYET@LR](https://user-images.githubusercontent.com/104543768/174510816-519766f7-54a3-49dc-83e7-5aa34934b55d.png)
