### ISSUE TITLE
The value of the dink protocol in the device management view is incorrect.

### ISSUE THREAD

**Issue by LX1203Hui** [dgiot/dgiot#487]
![image](https://user-images.githubusercontent.com/75428936/176384752-43fdf269-9fda-4146-ad32-c5914ad697bc.png)

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/176593941-c6d5567c-4b53-4a7c-acb5-5d804ab8451a.png)

fix
