### ISSUE TITLE
Interfaces manage tables that look like juxtapositions

### ISSUE THREAD

**Issue by Lunia-i** [dgiot/dgiot#51]
![image](https://user-images.githubusercontent.com/90381762/133038367-2283fa8d-3a78-4104-8fab-877929d4ec2b.png)

**Comment by h7ml** [comment]
?

**Comment by h7ml** [comment]
That's the way it is

**Comment by h7ml** [comment]
The parent and the drop-down, click on the parent and the drop-down are his subsets
