### ISSUE TITLE
about wechat login  bug in the latest version

### ISSUE THREAD

**Issue by 635168775** [dgiot/dgiot#602]
Hello,After upgrading to the latest version, what is the reason for the loss of these two values of wechat login in the log?thank you.

- dgiot version (e.g. `dgiot_ctl status`): 
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Erlang/OTP version (in case you build emqx from source code): 
- Others:
![7dab17f10274c22b3dc80f01e2c4e54](https://user-images.githubusercontent.com/3425179/188297851-91141749-d3bd-43d5-a7c9-34208883a936.png)

**Comment by dawnwinterLiu** [comment]
/data/dgiot/dgiot/etc/plugins/dgiot_http.conf  查看服务器这个文件是否与库上一致[dgiot_http.conf](https://github.com/dgiot/dgiot/blob/master/apps/dgiot_http/etc/dgiot_http.conf)
