### ISSUE TITLE
对接微信小程序

### ISSUE THREAD

**Issue by Keda-iot** [dgiot/dgiot#7]
你好，我是做智能家居的。设备目前已经支持WIFI和5G的连接。因为现在很多物联网厂家支持微信小程序的对接，请问你们是否支持mqtt协议实时订阅消息。

**Comment by yxc45678** [comment]
你好，目前我们已经完成了“借助 dgiot 消息服务器搭建微信小程序的mqtt服务器“的项目。如果您需要可以提供实际的效果图。具体问题具体分析，如果您还有别的顾虑或者问题我们将一一作答。

**Comment by yxc45678** [comment]
好的，发我一份你们实际案例的资料到我的邮箱。Keda-iot@163.com。然后我部分产品涉及TTL你们可以解决吧。

**Comment by Keda-iot** [comment]
好的，发我一份你们实际案例的资料到我的邮箱。Keda-iot@163.com。然后我部分产品涉及TTL你们可以解决吧

**Comment by yxc45678** [comment]
哦哦好的，我这里稍微整理一下资料发送到您的邮箱。然后您提的TTL我们也是支持的类似还有485、232串口都没有问题。同时您可以利用我们公有平台先连接设备看看效果。如果有进一步合作可以联系我们商务，资料都通过邮箱发送给您了。
