### ISSUE TITLE
检测任务

### ISSUE THREAD

**Issue by Keda-iot** [dgiot/dgiot#8]
![1627368798(1)](https://user-images.githubusercontent.com/87972919/127109240-d87f4d19-6235-44a6-8ee6-2eecbf92b617.jpg)
检测任务是没有完成吗，为什么部分页面和数据都切换不出来。报了500.然后这个表单系统具体制作有推荐的文档吗。

**Comment by crikayuan** [comment]
这个是做好了版本还在测试
